networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - gateway: 10.5.0.1
        subnet: 10.5.0.0/16
services:
  glusternode1:
    container_name: gluster1
    hostname: gluster1
    image: ankushbehl/gluster-centos
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    privileged: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  glusternode2:
    container_name: gluster2
    hostname: gluster2
    image: ankushbehl/gluster-centos
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    privileged: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  glusternode3:
    container_name: gluster3
    hostname: gluster3
    image: ankushbehl/gluster-centos
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    privileged: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  tendrlnode:
    container_name: tendrl_server
    hostname: tendrlserver
    image: ankushbehl/tendrl-centos
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    ports:
    - 2379:2379
    - 80:80
    - 3000:3000
    - 10080:10080
    privileged: true
    restart: always
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
version: '2'
