version: '2'
services:
  tendrlnode:
    privileged: true
    image: "ankushbehl/tendrl-centos"
    hostname: tendrlserver
    ports:
     - "2379:2379"
     - "80:80"
     - "3000:3000"
     - "10080:10080"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    container_name: tendrl_server
    restart: always
    depends_on:
     - glusternode3
     - glusternode2
     - glusternode1

  glusternode1:
    privileged: true
    image: "ankushbehl/gluster-centos"
    hostname: gluster1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    extra_hosts:
     - "tendrlserver:10.5.0.2"
    volumes:
     - /var/log/glusterfs:/var/log/glusterfs:z 
     - /var/lib/glusterd:/var/lib/glusterd:z
     - /etc/glusterfs:/etc/glusterfs:z
     - /dev/:/dev
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    container_name: gluster_storage1

  glusternode2:
    privileged: true
    image: "ankushbehl/gluster-centos"
    hostname: gluster2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    extra_hosts:
     - "tendrlserver:10.5.0.2"
    volumes:
     - /var/log/glusterfs1:/var/log/glusterfs:z
     - /var/lib/glusterd1:/var/lib/glusterd:z
     - /etc/glusterfs1:/etc/glusterfs:z
     - /dev/:/dev
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    container_name: gluster_storage2
    depends_on: 
     - glusternode1

  glusternode3:
    privileged: true
    image: "ankushbehl/gluster-centos"
    hostname: gluster3
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    extra_hosts:
     - "tendrlserver:10.5.0.2"
    volumes:
     - /var/log/glusterfs2:/var/log/glusterfs:z
     - /var/lib/glusterd2:/var/lib/glusterd:z
     - /etc/glusterfs2:/etc/glusterfs:z
     - /dev/:/dev
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    container_name: gluster_storage3
    depends_on: 
     - glusternode2
     - glusternode1

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
